### ISSUE TITLE
Remove version & dependencies from root package.json

### ISSUE THREAD

**Issue by emclaug2** [pxblue/react-native-component-library#109]
#### Describe the desired behavior
Angular and React component libraries use the components/package.json as the primary package.json.  It's used for versioning, listing dependencies, npm publishing.

#### Describe the current behavior
RN uses the root package.json instead of the components/package.json.

Why is this bad?
- The list of dependencies is now duplicated across the components/package.json and root package.json
- There's an extra step required to copy this file into the dist folder.

#### Is this request related to a current issue?
No

**Comment by joebochill** [comment]
Make sure to update the Publishing.md file to reflect the changes.
