### ISSUE TITLE
Should lint all the code

### ISSUE THREAD

**Issue by huayunh** [pxblue/react-native-component-library#12]
#### Describe the desired behavior
Need to resolve all the lint errors
![image](https://user-images.githubusercontent.com/8997218/75828336-988c9f00-5d79-11ea-9fb2-5e24fbc1da5a.png)

#### Describe the current behavior
There are currently 200+ lint errors

#### Is this request related to a current issue?
No

**Comment by joebochill** [comment]
Fixed in #24
