### ISSUE TITLE
Look into when to use React node, React Element or JSX Element as types

### ISSUE THREAD

**Issue by huayunh** [pxblue/react-native-component-library#15]
#### Describe the desired behavior
Need a unified rule for when to use React node, React Element or JSX Element as return types & propTypes

#### Describe the current behavior
Nearly everything is JSX Element

#### Is this request related to a current issue?
https://github.com/pxblue/react-component-library/issues/39

**Comment by joebochill** [comment]
Refer to the comments on https://github.com/pxblue/react-component-library/issues/39 for a description of the difference between the types.
