### ISSUE TITLE
Incorrect header background color for dark theme

### ISSUE THREAD

**Issue by joebochill** [pxblue/react-native-component-library#151]
#### Describe the bug
The getBackgroundColor returns the incorrect color when the theme is dark...this causes the color of the StatusBar content to be incorrect (black text on blue header).

#### What is the expected behavior?
This function should return `theme.colors.primaryBase` if it exists instead of `theme.colors.primary` as the default (see how we do it in the style rule).

#### What are the steps to reproduce?
1. Open up the demo
2. Switch to dark theme
3. Observe the status bar text colors

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/29152776/119007020-e1b91680-b95e-11eb-9e66-9432aa3ef6a4.png)

#### Anything else to add?
This was discovered in the auth workflow.

**Comment by huayunh** [comment]
Notice that the status bar is still doing black font color, bc it is pulling from the default blue dark theme and is using blue200 as its bg color. Need to pay attention to that
