### ISSUE TITLE
UserMenu has wrong icon color in dark theme

### ISSUE THREAD

**Issue by joebochill** [pxblue/react-native-component-library#154]
#### Describe the bug
UserMenu hardcodes the icon color default to gray[500]:
https://github.com/pxblue/react-native-component-library/blob/dev/components/src/core/user-menu/user-menu.tsx#L54

#### What is the expected behavior?
Dark themes should use black[200] as the default

#### What are the steps to reproduce?
1. Open the demo
2. Switch to dark theme
3. Observe the items in the bottomsheet of the UserMenu

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/29152776/119127226-0d410d00-ba02-11eb-90d3-d1caefb6faa5.png)

#### Anything else to add?
Discovered in the Auth Workflow example

**Comment by huayunh** [comment]
Change https://github.com/pxblue/react-native-component-library/blob/dev/components/src/core/user-menu/user-menu.tsx#L54 to be conditional based on the theme
