### ISSUE TITLE
Default Header background color is incorrect in dark themes

### ISSUE THREAD

**Issue by joebochill** [pxblue/react-native-component-library#155]
#### Describe the bug
Header defaults to using the primaryBase (blue) color in dark themes.

#### What is the expected behavior?
Should use the dark gray color (refer to our theme documentation).

#### What are the steps to reproduce?
1. Open the demo
2. Switch to dark theme
3. Observe the header is still blue

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/29152776/119129185-92c5bc80-ba04-11eb-829e-a378114506ad.png)

#### Anything else to add?
https://github.com/pxblue/react-native-component-library/blob/dev/components/src/core/header/header.tsx#L45

This was a recent change in our specs...we originally planned to keep the toolbars blue in dark which is what was implemented here.

**Comment by huayunh** [comment]
note that in the create account success screen we actually want this thing to be blue500 to match with that fancy wavy bg img
