### ISSUE TITLE
Empty State icon should be gray500

### ISSUE THREAD

**Issue by huayunh** [pxblue/react-native-component-library#173]
#### Describe the bug

Empty State icon is doing black500 by default

#### What is the expected behavior?

Should be gray500

#### Screenshots or links to minimum reproduction example

From Joe's sprint review demo
![image](https://user-images.githubusercontent.com/8997218/127656508-c52675b7-43ee-4740-837f-cf0a020e0ffe.png)

**Comment by emclaug2** [comment]
The code is set to use `theme.colors.text.secondary`, which is black[300].  Where is black[500] coming from? 

This looks like it should be a theme change.
