### ISSUE TITLE
Incorrect Default Icon color for ILI

### ISSUE THREAD

**Issue by joebochill** [pxblue/react-native-component-library#183]
The default icon color for InfoListItem in Figma is gray[500]/black[200] (light/dark). Our RN implementation uses theme.colors.text which is black[500]/black[50]. This is a bug and should be logged on the RN components library (make sure to add a note to be careful about the items in the drawer, because they should use different defaults)

The hero defaults to theme.colors.text, which I believe is correct according to the docs (there are actually no examples of Hero in figma with the default color, but I assume matching the text is the expected default). EmptyState should use a different shade of gray, but Huayun has already logged a bug for that.

_Originally posted by @joebochill in https://github.com/pxblue/react-native-showcase-demo/issues/19#issuecomment-893711853_

**Comment by daileytj** [comment]
This may require some changes in the theme as well. You may be able to pull a color from the 6.0.0 release though ¯\_(ツ)_/¯
