### ISSUE TITLE
Header actions should support controls other than avatars

### ISSUE THREAD

**Issue by joebochill** [pxblue/react-native-component-library#189]
#### Describe the desired behavior
User should be able to put simple controls in the Header Actions (like a switch). 

#### Describe the current behavior
Users can place any content they want into the header actions by using the `{component: <></>}` syntax, but the Header assumes that content passed in this way will be an avatar and configures the sizing to be 40x40 based on that.

#### Is this request related to a current issue?
This is an issue from CRDS/EMCB where the designs call for a Switch in the header actions.

#### Additional Context

Currently, if you pass in a 75px wide component:
![image](https://user-images.githubusercontent.com/29152776/129583701-ade3c09a-9011-42ca-b5a8-7e5011389112.png)

Should look like:
![image](https://user-images.githubusercontent.com/29152776/129583752-311959e5-0604-40d9-be12-ac02fb0ef108.png)

**Comment by daileytj** [comment]
@daileytj check to see if this is an issue with react as well.
