### ISSUE TITLE
Header should include a SafeAreaProvider

### ISSUE THREAD

**Issue by joebochill** [pxblue/react-native-component-library#193]
#### Describe the bug
When there is no SafeAreaProvider, the console throws an error when we try to access the safe area insets for calculating the height of the Header.

#### What is the expected behavior?
No errors

#### What are the steps to reproduce?
1. Start a new project with the cli
2. Run the project
3. Observe the error

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/29152776/131509121-f6cce94d-ccd6-47b8-9b1f-353369819c30.png)

**Comment by jeffvg** [comment]
same as this issue - https://github.com/pxblue/pxblue-cli/issues/99

**Comment by daileytj** [comment]
![Simulator Screen Shot - iPhone 12 - 2021-09-24 at 12 42 30](https://user-images.githubusercontent.com/13989985/134711149-0e444027-3085-4c3c-abc8-a117a46cdc13.png)
 This is the result of wrapping the header in SafeAreaProvider :(

**Comment by joebochill** [comment]
Per the recommendation for safe-area-context, it's better to wrap the application at the root that to have the provider inside of a component

**Comment by joebochill** [comment]
Per the recommendation/documentation for safe-area-context, it's better to wrap the application at the root that to have the provider inside of a component
