### ISSUE TITLE
Scorecard storybook has styling issues and collapsible header layout is not rendering in release/v5.4.1-react-native-components

### ISSUE THREAD

**Issue by bkarambe** [pxblue/react-native-component-library#231]
#### Describe the bug
- score card story has styling issues which is affecting the titles
- collapsible header layout story is throwing an error

#### What is the expected behavior?
- score card story should have titles rendering correctly
- collapsible header layout story should render without any errors

#### What are the steps to reproduce?
1. Checkout release/v5.4.1-react-native-components branch
2. yarn start:storybook
3. open navigation, click on ScoreCard and open with score badge story

#### Screenshots or links to minimum reproduction example
![144619681-44f2f0a1-2493-4660-b72e-9cf49926be8f](https://user-images.githubusercontent.com/25982779/144979171-61f0c3e9-144c-4e00-a8f1-9d5e7d564ccd.png)

![144617629-568eac0a-e3a2-45d0-942b-f185088b6803](https://user-images.githubusercontent.com/25982779/144979247-791b2892-e248-4d26-b8d3-3975764cf631.png)

**Comment by emclaug2** [comment]
Split this into 2 smaller issues. @emclaug2

**Comment by emclaug2** [comment]
The scorecard issue has something to do with the justification on the body part.

**Comment by emclaug2** [comment]
These bugs aren't present in the current version, latest major version.   

Going to close this issue.   Solution is to upgrade to latest.
