### ISSUE TITLE
divider is not working for DrawerHeader component

### ISSUE THREAD

**Issue by surajeaton** [pxblue/react-native-component-library#606]
#### Describe the bug / expected behavior
`divider` is not working for DrawerHeader component

This is found in Drawer Header Playground doc
#### What are the steps to reproduce?
1. [Go to...](https://brightlayer-ui-components.github.io/react-native/components/drawer-header/playground)
2. toggle `divider` value
3. Divider is not hiding in UI 

#### Screenshots / Screen recording

https://github.com/user-attachments/assets/76c173a8-f40f-4629-a49c-8befe46e0143

#### Code snippet / Link to minimum reproduction example

```
CODE HERE
```

**Comment by jvgreiner** [comment]
divider is not an optional prop for drawer header in RN components unlike the react drawer header
