### ISSUE TITLE
Users should be allowed to directly pass icons/components

### ISSUE THREAD

**Issue by huayunh** [pxblue/react-native-component-library#69]
#### Describe the desired behavior
Users should be able to pass in JSX.Elements directly to our components, e.g.:
```
<EmptyState icon={<MatIcon name={'error'} />} />
```
Similar to how the React library allows the users to supply anything that can be rendered (ReactNode)

#### Describe the current behavior
Icons have to be passed in using the IconClass prop, which has an unconventional usage/syntax that can be confusing for users.

#### Is this request related to a current issue?
No, but it comes from this PR: https://github.com/pxblue/doc-it/pull/224#discussion_r455742479

**Comment by joebochill** [comment]
This is tricky because if we allow them to pass in anything, we no longer have the ability to control the size. This is the primary motivator behind the whole `iconWrapper` utility. Due to the lack of size inheritance, if we allow them to pass in a ReactNode, all sizing becomes the end user's responsibility.

**Comment by joebochill** [comment]
See also the comment on #73 which has more details on the motivation/reasoning behind the iconWrapper utility function.

**Comment by joebochill** [comment]
What if we were to make our own icon package (yes another one) for RN similar to react-native-vector-icons. Users would be able to use them in the same way:
```
<PXBIcons name={'breaker'} size={120} color={'blue'} onPress={/* do something */}/>
```

We could then allow them to pass in icons in the typical way:
```
<EmptyState
    icon={<PXBIcon name={'breaker'}/>}
/>
```

and then inside the EmptyState (or whichever) component, we could clone it, put a size and a color on it (that we want) and then use that (similar to how we're cloning children in the Drawer component). We might need a little logic to handle the case where they passed in something other than an icon (e.g., what would be the repercussions on them passing in a text component and us cloning it and giving it a size prop).

We might even be able to do something like this without making our own library, potentially. But it would be nice if the API was the same for our icons and the react-native-vector-icons to reduce how much we have to check on our side.

**Comment by jeffvg** [comment]
moved to PXBLUE-1910
