### ISSUE TITLE
Header Landscape Issues

### ISSUE THREAD

**Issue by joebochill** [pxblue/react-native-component-library#76]
#### Describe the bug
Header is having some calculation issues with the height when used in landscape mode. 
On closer inspection it also looks like the background image is not doing 'cover' on wider screens.

#### What is the expected behavior?
Header should look correct when switching between portrait and landscape modes.

#### What are the steps to reproduce?
1. Open the showcase
2. Rotate the device

#### Screenshots or links to minimum reproduction example
When loaded in portrait and switched to landscape:
![image](https://user-images.githubusercontent.com/29152776/88919906-e7ac0280-d239-11ea-94f6-a23b04e67e5e.png)

When loaded in landscape:
![image](https://user-images.githubusercontent.com/29152776/88920116-4cfff380-d23a-11ea-98ad-c808ff2213cf.png)

When loaded in landscape and rotated to portrait:
![image](https://user-images.githubusercontent.com/29152776/88920155-5c7f3c80-d23a-11ea-8b03-bc6c251b52b9.png)

#### Environment

Only looked at this on iOS, but I suspect we'll see similar issues on Android.
		
#### Anything else to add?
I think we need to add some logic to detect the device orientation and recalculate the header height based on SafeAreaView, etc.

**Comment by huayunh** [comment]
Leave this here for now; consider doing an audit on our RN components for device orientation.

**Comment by huayunh** [comment]
Have a look and see if we can close this; looked fine in some recent PRs

**Comment by joebochill** [comment]
This is still goofy as of today.
