### ISSUE TITLE
Upgrade to RNP 4

### ISSUE THREAD

**Issue by joebochill** [pxblue/react-native-component-library#87]
#### Describe the desired behavior
Use the latest 4.x version of React Native Paper

#### Describe the current behavior
Using 3.x

#### Is this request related to a current issue?
No

#### Additional Context
We can go in and clean up a bunch of ts-ignore comments and/or unnecessary 'accessibilityStates' props now.

**Comment by huayunh** [comment]
Logged a new issue to the too groom queue PXBLUE-1659
